### ISSUE TITLE
Not setting key

### ISSUE THREAD

**Issue by ddevoss** [BrennenRocks/fishbowl-js#10]
I'm new to fishbowl, thanks a ton for making this. I was playing around yesterday and wasn't able to initialize my instance properly. After digging in I discovered that the 'statusCode' was being returned inside of the response from fishbowl which was throwing off your switch case.

Not sure if this is just my instance of fishbowl, or what's up, but I was able to fix it by changing line 244 in index.ts from:
`const fbData = Object.keys(data.FbiJson.FbiMsgsRs)[0];`
to: 
`const fbData = Object.keys(data.FbiJson.FbiMsgsRs).find(msg => msg != 'statusCode');`

I hope that helps anybody else running into this problem!

**Comment by BrennenRocks** [comment]
This is perfect. If you want to contribute and make a pull request that would be great. Otherwise I will put this in late tonight

**Comment by ddevoss** [comment]
#11 
Done, thanks again for the repo.
