### ISSUE TITLE
Use clear-text passowrd

### ISSUE THREAD

**Issue by smfelsher** [BrennenRocks/fishbowl-js#16]
According to Fishbowl Support:

_"In Fishbowl 21.12 we updated the encryption scheme we use for Fishbowl passwords and removed the requirement to send it as part of API calls. You'll just need to send the password as plain text and not MD5 hashed."_

It looks like the login request function needs to change, but how to handle the different versions of Fishbowl with how this library is implemented?

**Comment by BrennenRocks** [comment]
Hey @smfelsher I no longer make updates to this project as I no longer work at Fishbowl so I don't have the insider scoop to keep this project updated appropriately. I have no way of testing my changes to make sure they still work with Fishbowl

**Comment by smfelsher** [comment]
Understood. They are developing a RESTful API that will probably replace this interface; however, it does not yet have all of the Legacy API features. 

I've tweaked my local copy to send the password as clear text, so I am working around this issue. However, I would like to update the `fishbowl-js` library to account for this. I'll need to dig into the details, but maybe there is something in the initial connection response that would help identify the Fishbowl version. Based on the version, then the library could format the password appropriately. OR, maybe a fork of your library for the new version of Fishbowl. Just spit-balling some ideas.

Thank you for creating this library and good luck with your future endeavors!
