### ISSUE TITLE
Request sends back error 1111 for all requests

### ISSUE THREAD

**Issue by steven-parker** [BrennenRocks/fishbowl-js#2]
Changing the ID number in the constructor doesn't seem to help. No integrated apps are using the IDs picked either.
![Screen Shot 2019-10-28 at 3 17 11 PM](https://user-images.githubusercontent.com/17929358/67710338-243e8b00-f996-11e9-85ad-cf788bbdaad5.png)
![Screen Shot 2019-10-28 at 3 17 47 PM](https://user-images.githubusercontent.com/17929358/67710341-256fb800-f996-11e9-9867-db2c0c0ecf33.png)

**Comment by BrennenRocks** [comment]
@steven-parker I don't see a login request in your code. Can you be sure to login to Fishbowl using 
`fishbowl.sendRequest({ req: 'LoginRq' });` and then accept the app in Fishbowl itself and try again?

**Comment by steven-parker** [comment]
That works. Awesome. Thanks for that help
