### ISSUE TITLE
Incomplete data causing server hang

### ISSUE THREAD

**Issue by tylerhahn** [BrennenRocks/fishbowl-js#5]
Hi,
I've been using this package for awhile now and it's been a huge help.
I'm currently running it on a Node/Express server and running into some stability issues that I've been trying to debug for a bit.

I'm getting response data via ` this.connection.on('data'...`
but have recently noticed that the response is getting stuck waiting for ` resData.length === resLength.` 

I'm calling fb.sendRequest from an endpoint like this:

```
app.get("/products", (req, response)  => {
  fb.sendRequest({ req: "LoginRq" });

    fb.sendRequest(
      {
        req: "ExecuteQueryRq",
        options: {
          query: "select * from product"
        }
      },
      (err, res) => {
        if (err) {
          return response.status(err, 500);
        }
        return response.json(res);
      }
    );
});

```

I'm also seeing a bunch of previous requests in the reqQue that aren't being dequed and I'm wondering if that has something to do with this issue.

**Comment by BrennenRocks** [comment]
@tylerhahn Hey sorry I haven't replied, it's been a busy week!

When you call your endpoint does it just hang? Do you have exact steps to replicate?

**Comment by tylerhahn** [comment]
@BrennenRocks 
No worries! Thanks for the response.

The express server is pretty pretty boilerplate only contains the /products route above with no middleware or 3rd party packages.

The first time I make a request to the /products route I get a response with the requested data. Then if wait ~5-10min the same requests hangs and I need to restart the server to get a response again. The fishbowl log shows 'Waiting for more data from fishbowl' and no Node errors being reported. It also doesn't seem like a memory issue as I'm not seeing any spikes there as well.

**Comment by BrennenRocks** [comment]
@tylerhahn I'm having troubles replicating it.

But could you try changing up the index.js file in the node_modules/fishbowl-js/lib folder?
Give this a try, I'm wondering if something is getting an error and then any requests in the reqQueue are not being executed.

![image](https://user-images.githubusercontent.com/10799846/77781456-355df780-701b-11ea-941b-517ee229223e.png)

**Comment by wengyilun** [comment]
@BrennenRocks 
I was having a different issue getting the key populated correctly after login. And your updated snipped  seems to fix it. 👯  Thanks!!!
