### ISSUE TITLE
Help with displaying JSON results in HTML table format

### ISSUE THREAD

**Issue by rmit-hwilcox** [BrennenRocks/fishbowl-js#9]
First of all.... amazing work. I have been playing around with fishbowl-js for a few days now and am starting to get somewhere!

I've hit a major brick wall and just can seem to get my head around how to parse the request into a html table in node js.

I have successfully set up an express server in node js using visual studio 2019 and when I go to localhost:3000 i get the data punched out in a response shown below: 

> {"statusCode":1000,"Rows":[{"PARTID":"2","LOCATIONGROUPID":"1","QTY":"1644.607500000","id":"2","num":"ICFASTORANGE","description":"4LT DIVIDER PAD #30.1"},{"PARTID":"4","LOCATIONGROUPID":"1","QTY":"662.977140000","id":"4","num":"EMPICOLXC","description":"GARDINOL XC"},{"PARTID":"5","LOCATIONGROUPID":"1","QTY":"827.718270000","id":"5","num":"EMPIGENBB","description":"GARDIQUAT BBAU"},{"PARTID":"6","LOCATIONGROUPID":"1","QTY":"3690.751500000","id":"6","num":"SLES70","description":"GARDILENE SQ70"},{"PARTID":"7","LOCATIONGROUPID":"1","QTY":"2381.650000000","id":"7","num":"CL24/410WHSCREW","description":"24/410 WHITE RIBBED SCREW CAP"},{"PARTID":"11","LOCATIONGROUPID":"1","QTY":"407.000000000","id":"11","num":"BANTTERMITEKILL","description":"PERMETHRIN 100 g/L"},{"PARTID":"17","LOCATIONGROUPID":"1","QTY":"990.000000000","id":"17","num":"CU500PETCLBELL","description":"500ML PET CLEAR BELL ROUND BOTTLE"},{"PARTID":"19","LOCATIONGROUPID":"1","QTY":"522.584100000","id":"19","num":"CITAC","description":"CITRIC ACID `FINE'"},{"PARTID":"23","LOCATIONGROUPID":"1","QTY":"140.512820000","id":"23","num":"CITACMONO","description":"CITRIC ACID MONOHYDRATE"},{"PARTID":"24","LOCATIONGROUPID":"1","QTY":"15.771000000","id":"24","num":"SODTHIOSULPH","description":"SODIUM THIOSULPHATE CRYSTAL"},{"PARTID":"31","LOCATIONGROUPID":"1","QTY":"768.000000000","id":"31","num":"FGLOCTHKORAN4LT","description":"ORANGE HAND CLEAN 36253"},{"PARTID":"32","LOCATIONGROUPID":"1","QTY":"5801.155020000","id":"32","num":"STARCHCORN/1","description":"CORN STARCH - FINE"},{"PARTID":"33","LOCATIONGROUPID":"1","QTY":"162.477600000","id":"33","num":"MAGCARB","description":"MAGNESIUM CARBONATE LIGHT"},{"PARTID":"34","LOCATIONGROUPID":"1","QTY":"4.587040000","id":"34","num":"JASMINEOILCO","description":"JASMINE OIL 3% JOJOBA CERTIFIED ORGANIC"},{"PARTID":"35","LOCATIONGROUPID":"1","QTY":"0.730080000","id":"35","num":"CHAMOILCO","description":"CHAMOMILE OIL ROMAN 3% JOJOBA CERTIFIED ORGANIC"},{"PARTID":"36","LOCATIONGROUPID":"1","QTY":"201.722530000","id":"36","num":"AVOCADOOILCO","description":"AVOCADO OIL CERTIFIED ORGANIC"},{"PARTID":"37","LOCATIONGROUPID":"1","QTY":"0.969410000","id":"37","num":"GERANIUMOILCO","description":"GERANIUM OIL (EGYPT) CERTIFIED ORGANIC"},{"PARTID":"39","LOCATIONGROUPID":"1","QTY":"2441.600000000","id":"39","num":"CL46WHITE/1","description":"WHITE BASE FOR COMPOSITE CAN"},{"PARTID":"47","LOCATIONGROUPID":"1","QTY":"16.674000000","id":"47","num":"PLFS68159","description":"MEDICATED FRAGRANCE"},{"PARTID":"53","LOCATIONGROUPID":"1","QTY":"86.000000000","id":"53","num":"OCPL12X125","description":"RING EZE 125ML X 12 PLAIN #168"},{"PARTID":"55","LOCATIONGROUPID":"1","QTY":"181.391600000","id":"55","num":"BANTTERMITEKILLER","description":"PERMETHRIN 250 G/L"},{"PARTID":"56","LOCATIONGROUPID":"1","QTY":"103.195230000","id":"56","num":"GAFQUAT755N","description":"GAFQUAT 755N-P"},{"PARTID":"57","LOCATIONGROUPID":"1","QTY":"231.650000000","id":"57","num":"CU250PVCCL","description":"250ML PVC CLEAR OVAL BOTTLE  #391"},{"PARTID":"58","LOCATIONGROUPID":"1","QTY":"59.982000000","id":"58","num":"ROTDUST","description":"ROTENONE DUST 7%"},{"PARTID":"59","LOCATIONGROUPID":"1","QTY":"101.572600000","id":"59","num":"PROPGLY","description":"PROPYLENE GLYCOL USP/BP"},{"PARTID":"60","LOCATIONGROUPID":"1","QTY":"295.227128948","id":"60","num":"LACTICACID","description":"PURAC HS 88"},{"PARTID":"61","LOCATIONGROUPID":"1","QTY":"2749.500000000","id":"61","num":"LBRANTKILL1LTB","description":"ANT KILLER 1LT LABEL BACKS"},{"PARTID":"62","LOCATIONGROUPID":"1","QTY":"1510.600000000","id":"62","num":"LBRANTKILL750","description":"ANT KILL 750ml LABEL FRONTS"},{"PARTID":"63","LOCATIONGROUPID":"1","QTY":"710.600000000","id":"63","num":"LBRANTKILL750B","description":"ANT KILL 750ml LABEL BACKS"}, ect...

my code is as follows i have 2 files, one called app.js and another called index.js (code shown below):

```
app.js:

'use strict';
var debug = require('debug');
var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');

// uncomment after placing your favicon in /public
//app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', routes);
app.use('/users', users);

// catch 404 and forward to error handler
app.use(function (req, res, next) {
    var err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// error handlers

// development error handler
// will print stacktrace
if (app.get('env') === 'development') {
    app.use(function (err, req, res, next) {
        res.status(err.status || 500);
        res.render('error', {
            message: err.message,
            error: err
        });
    });
}

// production error handler
// no stacktraces leaked to user
app.use(function (err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
        message: err.message,
        error: {}
    });
});

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function () {
    debug('Express server listening on port ' + server.address().port);
});
```

index.js (code):

```
'use strict';
var express = require('express');
var router = express.Router();

/* GET home page. */

router.get(hwtest(), (req, response) => {

    const Fishbowl = require('fishbowl-js');

    const fb = new Fishbowl({
        host: 'localhost',
        port: 28192,
        IAID: 54321,
        IAName: 'Fishbowljs',
        IADescription: 'Fishbowljs helper',
        username: 'test',
        password: 'test',
        useLogger: true
    });

    fb.sendRequest({ req: "LoginRq" });

    fb.sendRequest(
        {
            req: "ExecuteQueryRq",
            options: {
                query: "select * from qtyonhand left join (select id, num, description from part) part on part.id=qtyonhand.PARTID"
            }
        },
        (err, res) => {
            if (err) {
                return response.status(err, 500);
            }
            return response.json(res);
        }
    );
    fb.sendRequest({ req: "LogoutRq" });
});

module.exports = router;

function hwtest() {
    return "/";
}
```

I have tried so many tutorials and solutions on "stackoverflow to dispaly json from mysql/database as html table in node js" and have no luck. 

Any help would be greatly appreciated

**Comment by BrennenRocks** [comment]
Are you asking how to display HTML from Nodejs?

Nodejs with express is a backend framework. You're going to want to create some front end to display the data retrieved from express.

You'll create an html file with a JavaScript file. In the JavaScript file you can use fetch to your router.get(hwtest()) endpoint. Documentation for fetch: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
Then manipulate your html from your JavaScript to display the data.

example would be
```
fetch('http://localhost:{PORT}/{API_ENDPOINT}')
  .then(res=> res.json())
  .then(data => {
    console.log(data);
    // Manipulate your html here to display the data from your express server
});
```

**Comment by rmit-hwilcox** [comment]
Thank you! Exactly the answer I have been looking for, sent me down the right rabbit hole :). I ended up using datatables:




    <table id="example" class="display" style="width:100%">
        <thead>
        </thead>
        <tbody>
        </tbody>
    </table>

    <script>
    fetch('http://localhost:3000/')
            .then(res => res.json())
            .then(data => {
                console.log(data);
            });

        $(document).ready(function () {
            $('#example').DataTable({
                "ajax": {
                    "url": "http://localhost:3000/",
                    "dataSrc": "Rows"
                },
                columns: [
                    { 'data': 'num' },
                    { 'data': 'description' },
                    { 'data': 'QTY' },
                ]
            });
        });
    </script>

</body>
</html>

**Comment by BrennenRocks** [comment]
Glad to hear it 🙂
